### ISSUE TITLE
Add `grattan_label` 

### ISSUE THREAD

**Issue by wfmackey** [grattan/grattantheme#100]
Wrapper around `geom_label_repel` that has Grattan defaults _and_ converts `size` to font size. 

Something like this has been handy in writing the data viz chapters:

```
grattan_label <- function(..., size = 18) {

  .size = size / ggplot2::.pt
  
geom_label_repel(..., 
           fill = "white",
           label.padding = unit(0.1, "lines"), 
           label.size = 0,
           size = .size)
}
```

I think it's structure will develop as I deal with more labelling in the book. eg maybe `grattan_label_bar` and `grattan_label_point` variations that take care of more of the defaults.

THOUGHTS?

**Comment by MattCowgill** [comment]
1. `geom_grattan_label()`
2. `grattan_label()`
3. `grattan_geom_label()`

whaddaya reckon

**Comment by wfmackey** [comment]
Hard `2`

**Comment by MattCowgill** [comment]
done in active PR, @wfmackey
