### ISSUE TITLE
Add ggtext support to type = "fullslide"

### ISSUE THREAD

**Issue by wfmackey** [grattan/grattantheme#105]
Allow coloured words in full-slide subtitles using the `ggtext` package. 

Need to:
- add check for `</` to identify a `ggtext` subtitle.
- use regex to tell the length-checker to chill out.
- add `theme(plot.subtitle = element_markdown())` to subtitle grob.
- note that `\n` doesn't work when `element_markdown()` is active, but `<br>` does, so will need to replace in update.

**Comment by MattCowgill** [comment]
This is cool

`"element_markdown" %in% attr(p$theme$plot.subtitle, "class")` is another way of doing the first bit

The `wrap_labs()` function might need a bit of work with this. It's slightly messy, though I did partially rewrite it for the `gganimate` stuff

**Comment by wfmackey** [comment]
Yep the %in% approach is neater.

**Comment by MattCowgill** [comment]
better:

```
inherits(p$theme$plot.subtitle, "element_markdown")
```

**Comment by MattCowgill** [comment]
this is all straightforward apart from the bit about checking the length of the title/subtitle if it includes markdown...

**Comment by wfmackey** [comment]
Closed with #178
