### ISSUE TITLE
create RStudio template for Powerpoint .Rmd docs

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattantheme#107]

**Comment by MattCowgill** [comment]
& update `make_slide()` and `make_presentation()` to reflect the new .pptx location

**Comment by wfmackey** [comment]
@MattCowgill what is this?

**Comment by MattCowgill** [comment]
ah I think my idea was to make it easy for people to create PPT decks from an RMarkdown doc by including a template. But I reckon best to abandon the idea - you've now got `grattan_save_pptx()` which is fine
