### ISSUE TITLE
create function to support ggtext legends

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattantheme#123]
not sure of the feasibility of this

The `labels` argument to `scale_colour_manual()` (etc.) can take a function that takes the breaks as input and returns labels as output.

This function would take the breaks, wrap them in html incl. the right colours

**Comment by MattCowgill** [comment]
doing this in a separate package, may import a function once stable https://github.com/MattCowgill/ggrichlegend

**Comment by wfmackey** [comment]
Yep good

**Comment by wfmackey** [comment]
Great

**Comment by wfmackey** [comment]
Gettin' there

**Comment by MattCowgill** [comment]
work will continue in `ggrichlegend`
