### ISSUE TITLE
Watermark doesn't work when type = "all" with png output. 

### ISSUE THREAD

**Issue by jonathananolan** [grattan/grattantheme#136]
Not a biggie but thought I'd mention.

**Comment by MattCowgill** [comment]
does it work with PDF?

**Comment by jonathananolan** [comment]
Sorry - yes it does work with pdf.

**Comment by MattCowgill** [comment]
Hi @jonathananolan it works fine for me with png and PDF. Can you do a reprex using the reprex package?

**Comment by MattCowgill** [comment]
``` r
library(grattantheme)
library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  theme_grattan()
```

![](https://i.imgur.com/c02tPSw.png)

``` r

grattan_save("test.png", type = "all", watermark = "DRAFT")
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MattCowgill** [comment]
Resulting files contain the watermark, eg:

![test_blog](https://user-images.githubusercontent.com/8002951/80555121-ae81ad80-8a12-11ea-919e-896486846835.png)
![test_normal](https://user-images.githubusercontent.com/8002951/80555132-b80b1580-8a12-11ea-9bfb-278fe48b13b7.png)

**Comment by MattCowgill** [comment]
I can't replicate this problem, @jonathananolan. Maybe it is a Windows thing? If so, could you please share some code to reproduce the problem & reopen the issue.
