### ISSUE TITLE
Input Notes/sources as a single box 

### ISSUE THREAD

**Issue by jonathananolan** [grattan/grattantheme#145]
I think it would be ace if notes and sources in ppt output were a single text box rather than a box for each line of text. Not sure how hard this is to do!

**Comment by MattCowgill** [comment]
Not possible when doing the slides this way (as editable vector graphics). 

I could do it if the graphs were state images (PNGs), but then any text on the slides (eg. annotations) wouldn't be editable.

If we output the graphs as editable vector graphics, each line of text is its own PPTX text box. This includes annotations that split over multiple lines.
