### ISSUE TITLE
`writeLines` should use `useBytes = TRUE`

### ISSUE THREAD

**Issue by HughParsonage** [grattan/grattantheme#161]
Here:

https://github.com/grattan/grattantheme/blob/4e6906b3f0570acc6e6edaea5104dba1fff0d847/R/grattan_save_pptx.R#L154

Otherwise risks an error in rmarkdown::render because of the wrong encoding on Windows.

**Comment by MattCowgill** [comment]
Thanks @HughParsonage, I'll make that change.
