### ISSUE TITLE
Gridlines are too thick/dark

### ISSUE THREAD

**Issue by wfmackey** [grattan/grattantheme#168]
We should change that.

**Comment by MattCowgill** [comment]
in the style guide, the package, or both? I think they're already thinner in the ggplot2 theme than in the style guide.

**Comment by wfmackey** [comment]
everywhere

**Comment by MattCowgill** [comment]
maybe we should just remove lines? They're already pretty light / thin...

**Comment by MattCowgill** [comment]
I actually think they're OK but wouldn't mind lightening them. I think they end up too dark/thick in PPT charts
