### ISSUE TITLE
Add frankenstein PPTX format

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattantheme#170]
16:9 orientation
25.4cm wide, 14.29 cm high

(cf. standard 16:9 template = 33.9 x 19 cm).

**Comment by MattCowgill** [comment]
is this a bad idea @wfmackey? I don't think the frankenstein format is going away, and it seems easier to me to just give in

**Comment by wfmackey** [comment]
nah I think better to cater to it

**Comment by wfmackey** [comment]
great stuff Cowgill
