### ISSUE TITLE
rewrite make_slide() and make_presentation() to write svg graphics using officer

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattantheme#46]
At the moment, `make_slide()` (and `make_presentation()`) writes a graph as a .png image, then uses RMarkdown to embed this image in a Powerpoint slide (with the title, subtitle, and caption extracted from the image and inserted as text). 

Outputting an .svg object rather than a .png may be preferable, as this makes the object 'editable' (sort of) in Powerpoint.

**Comment by MattCowgill** [comment]
what are your thoughts @wfmackey and interested onlooker @jonathananolan, should I do this

**Comment by wfmackey** [comment]
Yeah I think it's worth it. We always end up doing some post-production altering, and `svg`s are far nicer (`png` outputs are stodgy/reliant on exact h/w dimensions).

You should do it Matt.

**Comment by MattCowgill** [comment]
OK @wfmackey that's all the push I need. In the last week or so I've done a bunch of updates to readabs (getting ready for a new version) so I'm ready to do grattantheme stuff now

**Comment by MattCowgill** [comment]
Note to self: ggsave() supports svg, but they’re not editable. Need to do this via the officer package

**Comment by MattCowgill** [comment]
maybe could use https://github.com/tomwenseleers/export

**Comment by MattCowgill** [comment]
FYI @jonathananolan @wfmackey I investigated this properly this weekend. It works quite well, except for one thing: speaker notes. There's no way to edit speaker notes via `officer` (see https://github.com/davidgohel/officer/issues/117). 

This is important, because PDs (reasonably) insist on PPTX slides having speaker notes that list the title, subtitle, notes & source, plus the file path to the scrip that created the slide. I'm going to stick with creating Powerpoint files via RMd rather than `officer` for this reason (RMd allows speaker notes). If /when `officer` adds this feature, I'll switch.

**Comment by MattCowgill** [comment]
speaker notes were added in `{officer}` 0.4.2! https://github.com/davidgohel/officer/blob/master/NEWS.md
