### ISSUE TITLE
Incorporate left-alignment with theme rather than grob-hacking

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattantheme#96]
As of https://github.com/tidyverse/ggplot2/pull/3494, ggplot2 supports aligning labels to the outer boundary of the image, not the plotting area. This is currently implemented in `grattan_save()` through conversion with `ggplotGrob()`. Left-alignment should be added to `theme_grattan()` and removed from `grattan_save()` and related functions.

**Comment by MattCowgill** [comment]
will wait until this is in the CRAN version of ggplot2

**Comment by MattCowgill** [comment]
when this is on CRAN, we'll have a choice:

- require the latest ggplot2; or
- check for the version of ggplot2 and implement the `plot.title.position()` method for left-alignment if it's >= 3.2.2 or the current method if not

I lean towards option 1, views welcome @wfmackey 
We'll face similar choices with other ggplot2 API changes, like `expansion`

**Comment by wfmackey** [comment]
I'm strongly for requiring the latest CRAN version of `ggplot2`. 

Regularly updating packages is good practice, and this is a good channel to make a point of it.

**Comment by MattCowgill** [comment]
yep, cool, agreed
